import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import NextauthProvider from "@/providers/NextauthProvider";
import { Toaster } from "@/components/ui/toaster";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: {
    template: `%s | StorySpire`,
    default: "StorySpire",
  },
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <NextauthProvider>
        <body className={`${inter.className} min-h-[100svh]`}>
          {children}
          <Toaster />
        </body>
      </NextauthProvider>
    </html>
  );
}
